In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
import os 


In [3]:
data = pd.read_csv('experiment_data.csv', sep=',', index_col=0)

In [4]:
data.head()

max_force  max_lenght  max_time  section_area  is_valid
3-1    922.5591    2.064367    123.86            30     False
3-10   871.8252    2.029167    121.75            30      True
3-2    879.5913    1.945533    116.73            30      True
3-3    831.2734    1.874533    112.47            30      True
3-4    810.5214    1.835533    110.13            30     False

In [5]:
from sklearn.linear_model import LinearRegression

In [9]:
train_data = data.drop(data[data.section_area == 70].index)
train_data = train_data.drop(train_data[data.section_area == 60].index)

<ipython-input-9-988a9683d393>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  train_data = train_data.drop(train_data[data.section_area == 60].index)


max_force  max_lenght  max_time  section_area  is_valid
3-1    922.5591    2.064367    123.86            30     False
3-10   871.8252    2.029167    121.75            30      True
3-2    879.5913    1.945533    116.73            30      True
3-3    831.2734    1.874533    112.47            30      True
3-4    810.5214    1.835533    110.13            30     False
3-5    826.3668    1.999033    119.94            30      True
3-6    834.9133    1.857400    111.44            30     False
3-7    907.3512    2.056533    123.39            30     False
3-8    926.6042    2.097533    125.85            30     False
3-9    871.9587    1.943533    116.61            30      True
4-1   1032.5860    2.087867    125.27            40     False
4-2   1000.3650    1.907700    114.46            40      True
5-1   1406.2260    2.587367    155.24            50     False
5-10  1385.7630    2.580033    154.80            50      True
5-2   1308.4440    2.331033    139.86            50     False
5-3   1337.1210    2.347167    140.83            50     False
5-4   1458.0350    2.660700    159.64            50     False
5-5   1391.2260    2.514367    150.86            50     False
5-6   1357.4710    2.421067    145.26            50      True
5-7   1414.9570    2.506400    150.38            50      True
5-8   1367.8680    2.397867    143.87            50     False
5-9   1360.9350    2.478367    148.70            50     False

In [8]:
X_train = train_data.section_area
X_train = X_train.values
X_train = X_train.reshape(-1, 1)
X_train

array([[30],
       [30],
       [30],
       [30],
       [30],
       [30],
       [30],
       [30],
       [30],
       [30],
       [40],
       [40],
       [50],
       [50],
       [50],
       [50],
       [50],
       [50],
       [50],
       [50],
       [50],
       [50]])

In [7]:
y_train = train_data.max_force
y_train

3-1      922.5591
3-10     871.8252
3-2      879.5913
3-3      831.2734
3-4      810.5214
3-5      826.3668
3-6      834.9133
3-7      907.3512
3-8      926.6042
3-9      871.9587
4-1     1032.5860
4-2     1000.3650
5-1     1406.2260
5-10    1385.7630
5-2     1308.4440
5-3     1337.1210
5-4     1458.0350
5-5     1391.2260
5-6     1357.4710
5-7     1414.9570
5-8     1367.8680
5-9     1360.9350
Name: max_force, dtype: float64

In [8]:
regression = LinearRegression().fit(X_train, y_train)

In [9]:
regression.coef_

array([25.525407])

In [10]:
regression.intercept_

92.80015636363635

In [11]:
X_test = data[(data.section_area == 60) | (data.section_area == 70)].section_area.values
X_test = X_test.reshape(-1, 1)

In [12]:
y_predicted = regression.predict(X_test)
y_predicted

array([1624.32457636, 1624.32457636, 1624.32457636, 1624.32457636,
       1624.32457636, 1624.32457636, 1624.32457636, 1624.32457636,
       1624.32457636, 1624.32457636, 1879.57864636, 1879.57864636,
       1879.57864636, 1879.57864636, 1879.57864636, 1879.57864636,
       1879.57864636, 1879.57864636, 1879.57864636, 1879.57864636])

In [13]:
y_true = data[(data.section_area == 60) | (data.section_area == 70)].max_force.values
y_true

array([1636.944, 1591.741, 1672.614, 1667.053, 1734.743, 1685.746,
       1590.516, 1576.301, 1617.316, 1564.711, 1865.088, 1829.489,
       1815.942, 1891.834, 1828.607, 1792.026, 1877.844, 1821.631,
       1783.597, 1818.671])

In [14]:
from sklearn.metrics import r2_score

In [15]:
y_true

array([1636.944, 1591.741, 1672.614, 1667.053, 1734.743, 1685.746,
       1590.516, 1576.301, 1617.316, 1564.711, 1865.088, 1829.489,
       1815.942, 1891.834, 1828.607, 1792.026, 1877.844, 1821.631,
       1783.597, 1818.671])

In [16]:
y_predicted

array([1624.32457636, 1624.32457636, 1624.32457636, 1624.32457636,
       1624.32457636, 1624.32457636, 1624.32457636, 1624.32457636,
       1624.32457636, 1624.32457636, 1879.57864636, 1879.57864636,
       1879.57864636, 1879.57864636, 1879.57864636, 1879.57864636,
       1879.57864636, 1879.57864636, 1879.57864636, 1879.57864636])

In [17]:
r2_score(y_pred=y_predicted, y_true=y_true)

0.738095438954656

In [18]:
y_true.mean()

1733.1207000000002